### ISSUE TITLE
Dinner recipe

### ISSUE THREAD

**Issue by danielpmahoney** [IntroToCode/CodeMates5_Fall22#2]
## 💬 Discussion topic

Identify dinner recipe

## ❗ Potential issues

We might not agree on the best dinner recipe

## 👥 People to consult

@abianesucb for recipe

## 📃 Details

@abianesucb - Find recipe online & share link in Slack, Fill in recipe name & servings, Submit pull request for review by @mikahyden & @bpicciano, After review, @mikahyden will merge

@mikahyden - Fill in time to prepare, ingredients, Submit pull request for review by @bpicciano & @willmckelvey, After review, @bpicciano will merge

@bpicciano - Fill in equipment needed, Submit pull request for review by @willmckelvey & @danielpmahoney, After review, @willmckelvey will merge

@willmckelvey - Fill in steps for preparation, Submit pull request for review by @danielpmahoney & @abianesucb, After review, @danielpmahoney will merge

@danielpmahoney - Fill in notes & codemates, Submit pull request for review by @abianesucb & @mikahyden, After review, @abianesucb will merge

**Comment by abianesucb** [comment]
Updated 10/22/22 to expand on acceptance criteria and delineation of work

**Comment by abianesucb** [comment]
We finished the recipe!

**Comment by abianesucb** [comment]
Adding in discussion on pull requests from Slack prior to starting the assignment:

Alana Bianes (she/her)
  [8:31 AM](https://haasmba2023.slack.com/archives/C044R0JF6NM/p1666452682014019)
Honestly, I'm second guessing how we should be doing pull requests since Joe's pull request template says this: "_Pull Requests should include commits from each member of your group._". In order to follow that protocol, instead of forking, we could create a branch within the main repo, make all of our commits there and then one person creates a pull request. Thoughts? (edited) 


Mika Hyden (she/her)
  [3:07 PM](https://haasmba2023.slack.com/archives/C044R0JF6NM/p1666476474067159)
Hmm I think that Joe basically already made the main branch, which is the readme file for us to update? (does that sound right?)
So then we can each make our assigned commits / pull requests directly to the readme file. Looks like I'm able to add in my sections for dinner recipe (time and ingredients) as a commit/new branch and then submit a pull request from here. Does that look right?
